/////////////////////////////////////////////////////////////////
//															   //
// This code is generated by a tool                            //
// https://github.com/StevenThuriot/dotnet-openapi-generator   //
//															   //
/////////////////////////////////////////////////////////////////

#nullable enable

#pragma warning disable CS8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.

namespace CE.Assessment.Infrastructure.WebClients.ChannelEngine.Models;

[System.CodeDom.Compiler.GeneratedCode("dotnet-openapi-generator", "8.0.0-preview.15+2dc8cfca012adb9b7e1a243f167db99da7b5cfe4")]
[System.Text.Json.Serialization.JsonConverter(typeof(GenderEnumConverter))]
public enum Gender
{
	MALE,
	FEMALE,
	NOT_APPLICABLE,
}

public static class GenderFastEnum
{
     public static string ToString(Gender value) => value switch
     {
         Gender.MALE => "MALE",
         Gender.FEMALE => "FEMALE",
         Gender.NOT_APPLICABLE => "NOT_APPLICABLE",
         _ => throw new System.NotSupportedException(value + " is not a supported Enum value")
     };

     public static Gender FromString(string? value) => value switch
     {
         "MALE" => Gender.MALE,
         "FEMALE" => Gender.FEMALE,
         "NOT_APPLICABLE" => Gender.NOT_APPLICABLE,
         _ => throw new System.NotSupportedException((value ?? "NULL") + " is not a supported Enum value")
     };
}

public class GenderEnumConverter : System.Text.Json.Serialization.JsonConverter<Gender>
{
    public override Gender Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
    {
        return GenderFastEnum.FromString(reader.GetString());
    }

    public override void Write(System.Text.Json.Utf8JsonWriter writer, Gender value, System.Text.Json.JsonSerializerOptions options)
    {
        writer.WriteStringValue(GenderFastEnum.ToString(value));
    }
}
