/////////////////////////////////////////////////////////////////
//															   //
// This code is generated by a tool                            //
// https://github.com/StevenThuriot/dotnet-openapi-generator   //
//															   //
/////////////////////////////////////////////////////////////////

#nullable enable

#pragma warning disable CS8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.

using CE.Assessment.Infrastructure.WebClients.ChannelEngine.Models;

namespace CE.Assessment.Infrastructure.WebClients.ChannelEngine.Models;

[System.CodeDom.Compiler.GeneratedCode("dotnet-openapi-generator", "8.0.0-preview.15+2dc8cfca012adb9b7e1a243f167db99da7b5cfe4")]
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public sealed class MerchantProductExtraDataItemRequest : __ICanIterate
{
    public MerchantProductExtraDataItemRequest() { }

    [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    [System.Text.Json.Serialization.JsonConstructor]
    public MerchantProductExtraDataItemRequest(string key, ExtraDataType type, bool isPublic)
    {
        Key = key;
        Type = type;
        IsPublic = isPublic;
    }

    public required string Key { get; set; }
    public string? Value { get; set; }
    public required ExtraDataType Type { get; set; }
    public required bool IsPublic { get; set; }
    public string? LanguageIsoCode { get; set; }

    System.Collections.Generic.IEnumerable<(string name, object? value)> __ICanIterate.IterateProperties()
    {
        yield return ("Key", Key);
        yield return ("Value", Value);
        yield return ("Type", Type switch
        {
            ExtraDataType.TEXT => "TEXT",
            ExtraDataType.NUMBER => "NUMBER",
            ExtraDataType.URL => "URL",
            ExtraDataType.IMAGEURL => "IMAGEURL",
            _ => null
        });
        yield return ("IsPublic", IsPublic);
        yield return ("LanguageIsoCode", LanguageIsoCode);
    }
}
