/////////////////////////////////////////////////////////////////
//															   //
// This code is generated by a tool                            //
// https://github.com/StevenThuriot/dotnet-openapi-generator   //
//															   //
/////////////////////////////////////////////////////////////////

#nullable enable

#pragma warning disable CS8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.

using CE.Assessment.Infrastructure.WebClients.ChannelEngine.Models;

namespace CE.Assessment.Infrastructure.WebClients.ChannelEngine.Models;

[System.CodeDom.Compiler.GeneratedCode("dotnet-openapi-generator", "8.0.0-preview.15+2dc8cfca012adb9b7e1a243f167db99da7b5cfe4")]
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public sealed class MerchantOfferStockUpdateRequest : __ICanIterate
{
    public MerchantOfferStockUpdateRequest() { }

    [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    [System.Text.Json.Serialization.JsonConstructor]
    public MerchantOfferStockUpdateRequest(string merchantProductNo, System.Collections.Generic.List<MerchantStockLocationUpdateRequest> stockLocations)
    {
        MerchantProductNo = merchantProductNo;
        StockLocations = stockLocations;
    }

    public required string MerchantProductNo { get; set; }
    public required System.Collections.Generic.List<MerchantStockLocationUpdateRequest> StockLocations { get; set; }

    System.Collections.Generic.IEnumerable<(string name, object? value)> __ICanIterate.IterateProperties()
    {
        yield return ("MerchantProductNo", MerchantProductNo);
        yield return ("StockLocations", StockLocations);
    }
}
