/////////////////////////////////////////////////////////////////
//															   //
// This code is generated by a tool                            //
// https://github.com/StevenThuriot/dotnet-openapi-generator   //
//															   //
/////////////////////////////////////////////////////////////////

#nullable enable

#pragma warning disable CS8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.

namespace CE.Assessment.Infrastructure.WebClients.ChannelEngine.Models;

[System.CodeDom.Compiler.GeneratedCode("dotnet-openapi-generator", "8.0.0-preview.15+2dc8cfca012adb9b7e1a243f167db99da7b5cfe4")]
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public sealed class ProductCreationResult : __ICanIterate
{
    public ProductCreationResult() { }

    [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    [System.Text.Json.Serialization.JsonConstructor]
    public ProductCreationResult(int rejectedCount, int acceptedCount)
    {
        RejectedCount = rejectedCount;
        AcceptedCount = acceptedCount;
    }

    public required int RejectedCount { get; set; }
    public required int AcceptedCount { get; set; }
    public System.Collections.Generic.List<ProductMessage>? ProductMessages { get; set; }

    System.Collections.Generic.IEnumerable<(string name, object? value)> __ICanIterate.IterateProperties()
    {
        yield return ("RejectedCount", RejectedCount);
        yield return ("AcceptedCount", AcceptedCount);
        yield return ("ProductMessages", ProductMessages);
    }
}
