/////////////////////////////////////////////////////////////////
//															   //
// This code is generated by a tool                            //
// https://github.com/StevenThuriot/dotnet-openapi-generator   //
//															   //
/////////////////////////////////////////////////////////////////

#nullable enable

#pragma warning disable CS8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.

using CE.Assessment.Infrastructure.WebClients.ChannelEngine.Models;

namespace CE.Assessment.Infrastructure.WebClients.ChannelEngine.Models;

[System.CodeDom.Compiler.GeneratedCode("dotnet-openapi-generator", "8.0.0-preview.15+2dc8cfca012adb9b7e1a243f167db99da7b5cfe4")]
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public sealed class ProductMessage : __ICanIterate
{
    public string? Name { get; set; }
    public string? Reference { get; set; }
    public string? KeyReference { get; set; }
    public System.Collections.Generic.List<string>? Warnings { get; set; }
    public System.Collections.Generic.List<string>? Errors { get; set; }

    System.Collections.Generic.IEnumerable<(string name, object? value)> __ICanIterate.IterateProperties()
    {
        yield return ("Name", Name);
        yield return ("Reference", Reference);
        yield return ("KeyReference", KeyReference);
        yield return ("Warnings", Warnings);
        yield return ("Errors", Errors);
    }
}
