# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-and-test

on: workflow_call 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test CE.Assessment.sln --no-build --verbosity normal --results-directory ../../TestResults -p:CollectCoverage=true -p:CoverletOutput=../../TestResults/coverage.xml -p:MergeWith=../../TestResults/coverlet.json  -p:CoverletOutputFormat=cobertura -maxcpucount:1
    - name: Store code coverage file
      uses: actions/upload-artifact@v3
      with:
        name: cover-${{ github.sha }}
        path: ${{ env.working-directory }}/TestResults/coverage.xml
        if-no-files-found: error
