# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: unit-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
  coverage:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: get coverage file
      uses: actions/download-artifact@v3
      with:
        name: cover-${{ github.sha }}
    - name: Show downloaded files
      run: ls -R  
    - name: Update Coverage Badge
      # https://github.com/GaelGirodon/ci-badges-action
      uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: f220611158dc6e68b5920a450054fff7
        token: ${{ secrets.GIST_TOKEN }}
      
            
             
            
